#!/usr/bin/env bash

set -e
echo '--- :house_with_garden: Setting up the environment'

. "$HOME/.asdf/asdf.sh"
asdf local erlang 21.3
asdf local python 3.7.3
asdf local ruby 2.6.2
asdf local elixir 1.8.2-opt-21
